{ inputs, outputs, lib, pkgs, ... }:{
  environment.systemPackages = with pkgs; [
    python313Packages.meshtastic
    wsjtx
    fldigi
    hamlib
    soundmodem
    direwolf
    flrig
    js8call
    digiham
    pat
	  minicom
    qlog
    contact
    nanovna-saver
    sdrpp
    sdrplay
    sdrangel
    sdr-j-fm
    hackrf
    soapyrtlsdr
    rtl-sdr-librtlsdr
    gnuradioPackages.osmosdr
    soapyremote
    nrsc5
    gqrx
    gnuradio
    quisk
    qradiolink
    fm-tune
    airspy
    inspectrum
    gnuradioPackages.lora_sdr
    qsstv
    gridtracker
    xastir
    svxlink
    tshark
  ];
}
